{
 "title": "DNSdist",
 "time": { "from": "2018-10-12T12:50:00.000Z", "to": "2018-10-12T16:00:00.000Z" },
 "panels": [
  {
   "title": "Router Taffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "In WAN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "interface",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.10.60.1" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Fa0/1" }
     ]
    },
    {
     "alias": "Out WAN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.10.60.1" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Fa0/0" }
     ]
    },
    {
     "alias": "Out LAN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.10.60.1" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Fa0/1" }
     ]
    },
    {
     "alias": "IN LAN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.10.60.1" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Fa0/1" }
     ]
    }
   ]
  },
  {
   "title": "Switches Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "In $tag_agent_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" }
     ],
     "measurement": "interface",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "!=", "value": "10.10.60.1" }
     ]
    },
    {
     "alias": "Out $tag_agent_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" }
     ],
     "measurement": "interface",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "!=", "value": "10.10.60.1" }
     ]
    }
   ]
  },
  {
   "title": "Ping latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Queries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(dnsdist.dnsloadbalancer.main.servers.127_0_0_1:5353.queries)"
    },
    {
     "target": "aliasByMetric(dnsdist.dnsloadbalancer.main.rdqueries)"
    }
   ]
  },
  {
   "title": "Queries Per Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(dnsdist.dnsloadbalancer.main.frontends.*.*, 4)"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(dnsdist.dnsloadbalancer.main.cache-hits)"
    },
    {
     "target": "aliasByMetric(dnsdist.dnsloadbalancer.main.cache-misses)"
    },
    {
     "target": "aliasByMetric(dnsdist.dnsloadbalancer.main.self-answered)"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(dnsdist.dnsloadbalancer.main.responses)"
    },
    {
     "target": "aliasByMetric(dnsdist.dnsloadbalancer.main.self-answered)"
    },
    {
     "target": "aliasByMetric(dnsdist.dnsloadbalancer.main.servfail-responses)"
    }
   ]
  },
  {
   "title": "Drops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(dnsdist.dnsloadbalancer.main.acl-drops)"
    },
    {
     "target": "aliasByMetric(dnsdist.dnsloadbalancer.main.block-filter)"
    },
    {
     "target": "aliasByMetric(dnsdist.dnsloadbalancer.main.dyn-blocked)"
    },
    {
     "target": "aliasByMetric(dnsdist.dnsloadbalancer.main.rule-drop)"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(dnsdist.dnsloadbalancer.main.latency-avg100)"
    },
    {
     "target": "aliasByMetric(dnsdist.dnsloadbalancer.main.latency-avg1000)"
    },
    {
     "target": "aliasByMetric(dnsdist.dnsloadbalancer.main.latency-avg10000)"
    },
    {
     "target": "aliasByMetric(dnsdist.dnsloadbalancer.main.latency-avg1000000)"
    }
   ]
  },
  {
   "title": "Carbon Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(carbon.agents.management_dnsathon-a.cpuUsage)"
    },
    {
     "target": "aliasByMetric(carbon.agents.management_dnsathon-a.memUsage)"
    },
    {
     "target": "aliasByMetric(carbon.agents.management_dnsathon-a.avgUpdateTime)"
    }
   ]
  }
 ]
}